import{i as l,S as d}from"./assets/vendor-0fc460d7.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&t(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();function f(a){const n=`https://pixabay.com/api/?key=44760113-b733d2f51a4c6409aa3483a05&q=${a}&image_typephoto&orientation=horizontal&safesearch=${!0}`;return fetch(n).then(i=>{if(!i.ok)throw new Error(i.status);return i.json()})}l.settings({timeout:2500,resetOnHover:!0,transitionIn:"flipInX",transitionOut:"flipOutX",position:"topRight",titleSize:25,messageSize:25,backgroundColor:"rgba(255, 182, 66, 0.8)"});var g=new d(".gallery a",{captionDelay:200,captionsData:"alt"});const u=document.querySelector(".gallery");u.addEventListener("submit",m);function m(a){const o=document.getElementsByClassName(".gallery");o.innerHTML="";const s=a.map(t=>` 
    <li class="gallery-item">
    <a class="gallery-link" href="${t.largeImageURL}">
    <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}" title="${t.name}"/></a>
    <div class="gallery-paragraf">
    <p class="gallery-commant">likes ${t.likes}</p>
    <p class="gallery-commant">views ${t.views}</p>
    <p class="gallery-commant">comments ${t.comments}</p>
    <p class="gallery-commant">downloads ${t.downloads}</p>
    </div>
    </li> 
     `).join("");u.insertAdjacentHTML("beforeend",s),g.refresh()}const c={gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")};function y(a){switch(a){case"outdata":l.warning({title:"Error",message:"Введіть данні для пошуку!"});break;case"nodata":l.warning({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});break;default:l.error({title:"Error",message:"Щось пішло не так. Ми працюемо над вирішенням питання!"});break}}const p=document.querySelector(".uzers-form-image");p.addEventListener("submit",h);function h(a){if(a.preventDefault(),!a.target.searchQuery.value){y("outdata");return}c.gallery.innerHTML="",c.loader.classList.add("loader");const s=a.currentTarget,t=s.elements.searchQuery.value.toLowerCase().trim();f(t).then(e=>{m(e.hits)}).catch(e=>console.error(e)).finally(()=>s.reset())}
//# sourceMappingURL=commonHelpers.js.map
